### ISSUE TITLE
`ITKVideoCore` Python module not available in ITK v5.3rc03

### ISSUE THREAD

**Issue by tbirdso** [KitwareMedical/ITKUltrasound#175]
## Description

The recent ITKUltrasound v0.5.1 release seems to add a wrapping dependency on the ITKVideoCore module, which is typically built as part of ITK but seems to not be included in the ITK v5.3rc03 release.

## Steps to reproduce
1. `python -m pip install itk==v5.3rc03`
2. `python -m pip install itk-ultrasound==v0.5.1`
3. Launch Python console
4. `import itk`
5. `itk.auto_progress(2)`
6. `itk.BModeImageFilter` (or any other class that requires ITKUltrasound to be loaded)

## Observed Output

```py
Loading SplitComponents... done
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\itk\support\lazy.py", line 137, in __getattribute__
    base.itk_load_swig_module(module, namespace)
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\itk\support\base.py", line 102, in itk_load_swig_module
    itk_load_swig_module(dep, namespace)
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\itk\support\base.py", line 98, in itk_load_swig_module
    l_data = itk_base_global_module_data[name]
KeyError: 'ITKVideoCore'
```

## Other Notes
Two possible paths forward:
- Not sure why the ITKVideoCore dependency is now showing up in the Python module when video-related classes were added last year, may be able to dig through and remove the Python dependency
- Otherwise the fix may lie in adding an `itk-video` Python distribution, which does not seem to be built as a standard ITK Python module right now

**Comment by tbirdso** [comment]
@dzenanz @thewtex Do you perhaps have insight into why we do not distribute an `itk-video` Python module at the moment? Would it be significant effort to add?
